 import 'package:recipe_app/model/local_recipe_model/cuisine_model.dart';
import 'package:recipe_app/model/local_recipe_model/meals_model.dart';

import 'category_model.dart';

const categories = [
  Category(imageUrl: 'assets/images/breakfast.png', id: 'a1', title: 'Breakfast'),
  Category(imageUrl: 'assets/images/lunch2.png', id: 'a2', title: 'Lunch'),
  Category(imageUrl: 'assets/images/dinner.png', id: 'a3', title: 'Dinner'),
  Category(imageUrl: 'assets/images/deserts.png', id: 'a4', title: 'Dessert'),
  Category(imageUrl: 'assets/images/snacks.png', id: 'a5', title: 'Snacks'),
  Category(imageUrl: 'assets/images/drink.png', id: 'a6', title: 'Drinks')
];

const cuisines = [
  CuisineModel(imageUrl: '', title: 'InterContinental', id: 'b1', subTitle: 'Access a list of International Recipes'),
  CuisineModel(imageUrl: '', title: 'Nigerian', id: 'b1', subTitle: 'Access a list of Nigerian Recipes')
];

final dummyMeals = [
  MealsModel(
      id: 'c1',
      title: 'Amala and Ewedu ',
      videoUrl: 'https://www.youtube.com/watch?v=xIxmLk2miqw',
      instructions: [
        "1. Thoroughly wash the Ewedu leaves and remove and discard the tough stems.",
        "2. Add the leaves and 2 cups of water to a medium-sized pot and bring to a boil. When the leaves are cooked, take them off the heat to cool a bit then use a mortar and pestle to pound the leaves along with the locust beans (iru).",
        "3. Alternatively, you can add the cooked leaves and locust beans to a blender along with about 1/2 cup of the cooking water from the leaves and pulse-blitz to a smooth puree. Add the water gradually to make sure it's not too watery.",
        "4. Transfer the Ewedu in a pan and add the crayfish, the boullion cube and salt to you liking. Mix everything well and heat it throughout then turn off the heat and let it sit for 3 minutes to steam, stirring occasionally. Do not overcook the mixture or the Ewedu will go brown.",
        "How to Make Amala:",
        "1. Add water to a medium pot and bring it to a rolling boil. Add the yam flour gradually, stirring continuously to break any lumps that might form.",
        "2. Adjust the consistency with more flour (if too thin) or more water (if too thick).",
        "3. Stir vigorously, cover with a lid and cook for 10 minutes until firm.",
        "4. Let the Amala cool and form balls in your hands. Wrap them up in nylon wrap.",
        "5. Serve the delicious Ewedu soup with Amala and enjoy!",
      ],
      ingredients: [ '1 big bunch ewedu leaves',
        '2 cups water',
        '1 tbsp locust beans (iru)',
        '1 tbsp ground crayfish (heaped)',
        '1 bouillon cube (1/2 maggi crayfish flavor)',
        'salt to taste,',
        'For Amala',
        '2 cups yam flour',
        '2 cups water',
      ],
      prepTimeMinutes: 5,
      cookTimeMinutes: 30,
      servings: 3,
      cuisine: 'Nigerian_Yoruba',
      caloriesPerServings: 5,
      rating: 4.5,
      imgUrl: 'https://www.chefspencil.com/wp-content/uploads/Amala-and-Ewedu-Soup.jpg.webp',
  ),
  MealsModel(
      id: 'c2',
      title: 'Ofada Stew',
      videoUrl: 'https://www.youtube.com/watch?v=Y13iS68sKbE',
      instructions: [ "Cut the peppers, and 2 red onion into small chunks, and blend roughly",
        "Boil the blended peppers on medium high heat till it reduces to a paste",
        "While the peppers are reducing, slice 2 red onions and set aside",
        "In separate pot, saute the sliced red onions in palm oil on medium heat til the onions turn slightly brown.",
        "Add in the cleaned smoked dried fish, the shrimp and continue to cook for another 10 minutes.",
        "Add in the reduced pepper paste, turn the heat down to low-medium, and continue cooking for 10 minutes. Add in the braised goat meat and the braising liquid and continue cooking for 15 minutes.",
        "After 15 minutes of cooking, add in the iru and bouillon, stir, and continue cooking until the stew separates from the oil (this could take about 10 minutes).",
        "Serve with boiled ofada rice or white rice",
      ],
      ingredients: ["7 large bell peppers",
        "3 scotch bonnet peppers",
        "4 large red onions",
        "2 lbs braised goat meat (braised with 1 red onion, 1 scotch bonnet pepper, 1 tsp salt and 1 tsp bouillon)",
        "80 grams cleaned smoked dried fish (about 0.17lbs)",
        "20 grams smoked dried shrimp about (0.04 lbs)",
        "½ cup palm oil",
        "2 tsps bouillon",
        "salt to taste",
        "1 tbsp Iru (fermented locust beans) (optional)",
      ],
      prepTimeMinutes:10,
      cookTimeMinutes: 45,
      servings: 4,
      cuisine: 'Nigerian-Yoruba',
      caloriesPerServings: 6,
      rating: 4.5,
      imgUrl: 'https://lowcarbafrica.com/wp-content/uploads/2020/06/Ofada-Stew-Ayamase-Stew-featured.jpg'),
  MealsModel(
      id: 'c3',
      title: 'Gizdodo',
      videoUrl: 'https://www.youtube.com/watch?v=_jC-ofeZTXM',
      instructions: [
        "Wash and clean the gizzards thoroughly.",
        "Place the gizzards inside the cooking pot and add diced onions, 1 seasoning cube, curry powder, thyme, and salt to taste.",
        "Add water to the same level as the gizzards and cook for about 40 minutes or until tender.",
        "Preheat some cooking oil and fry the gizzards till brown.",
        "Cut the plantain into bite-size cubes.",
        "Reduce the amount of oil by half.",
        "Add the remaining onion, tomatoes, and the chopped scotch bonnet pepper.",
        "Once the vegetables are cooked, add the gizzard, plantain, and sliced green bell pepper.",
        "Remove your gizdodo from heat and serve.",
      ],
      ingredients: [
        "1 Pound Gizzards",
        "2 Plantains Ripe",
        "4 Tomatoes Any Ripe and juicy Tomato will work",
        "Vegetable Oil Enough for frying",
        "Chicken stock",
        "1 Teaspoon Curry Powder Divided in two",
        "1 Tsp Thyme Divided in two",
        "Water For boiling the Gizzards",
        "2 Seasoning Cubes",
        "Salt to Taste",
        "Green Bell Pepper, Yellow Bell Pepper and Orange bell peppers Diced",
        "1 Habanero pepper Minced",
        "1 Large Onion (Diced) Divided in two",
      ],
      prepTimeMinutes: 5,
      cookTimeMinutes: 55,
      servings: 2,
      cuisine: 'Nigerian',
      caloriesPerServings: 2,
      rating: 4.5,
      imgUrl: 'https://img-global.cpcdn.com/recipes/2b168a6ce1fd81a7/680x482cq70/gizdodo-recipe-main-photo.jpg'
  ),
  MealsModel(
      id: 'c3',
      title: 'Asun',
      videoUrl: 'https://www.youtube.com/watch?v=81lrxpl0jVk',
      instructions: ["Before you make Asun:",
        "Cut the goat meat into big chunks. Make sure you cut the chunks with the goat skin. If the skin is not there, it won't be the real deal Asun.",
        "Wash and put the goat meat chunks in a bowl.",
        "Add the thyme and black pepper; crush and add the stock cubes. Feel free to add other spices and ingredients that you use to marinate meat.",
        "Mix the spices and the goat meat by gently rubbing with your hands.",
        "Cover the bowl with a thin film. Put in the fridge and leave to marinate for about 1 hour.",
        "In my opinion, marinating beef and other kinds of meat is completely optional so you can skip the marinating process and go straight to cooking the goat meat.",
        "Pound or blitz the habanero (scotch bonnet) peppers and set aside.",
        "Cut 1 onion into 4 big chunks.",
        "Making the Asun:",
        "After about 1 hour or the number of hours you chose to marinate the goat meat, put the meat in a pot. Use a pressure cooker if you have one because goat meat is quite tough and you will save lots of gas and electricity.",
        "Pour water to just half of the level of the goat meat, add the big chunks of onion and start cooking at medium heat. You do not want a lot of water because you want the water to dry up by the time the goat meat is well done.",
        "When the goat meat is well done, remove the big chunks of onions and add salt to taste.",
        "Increase the heat to high and stir constantly till all the remaining liquid in the pot is absorbed. You don't want to lose any flavour by pouring away the goat meat stock.",
        "Lay the goat meat flat on your oven rack.",
        "Grill/Broil in the oven at 180°C or 350°F till the meat is brown all over. You will need to turn them from time to time. The meat should not be dry. This takes a maximum of 15 minutes with my oven.",
        "While you are grilling the meat, wash, cut and thread the green bell pepper, red bell pepper and the remaining onion on toothpicks.",
        "When the meat it well grilled/broiled, heat the vegetable oil in a dry clean pot.",
        "Add the pepper and the thick stock from cooking the meat (if any) and fry for a bit.",
        "Add the grilled goat meat.",
        "Stir very well till the pepper is evenly distributed on the goat meat. The vegetable oil ensures that this happens and gives the Asun a nice glow.",
        "That's it! Serve with the threaded vegetables.",
      ],
      ingredients: [
        "1.2kg (2.6 lbs) goat meat (cut with the skin)",
        "2 habanero peppers (or to your taste)",
        "1 medium onion",
        "3 big stock cubes",
        "1 teaspoon thyme",
        "Salt (to taste)",
        "1 cooking spoon vegetable oil",
        "Black pepper (optional)",
        "To garnish:",
        "1 medium onion",
        "1 small green bell pepper",
        "1 small red bell pepper",
      ],
      prepTimeMinutes: 9, cookTimeMinutes: 40,
      servings: 3,
      cuisine: 'Nigeria',
      caloriesPerServings: 6,
      rating: 4.5,
      imgUrl: 'https://th.bing.com/th/id/OIP.zLPRGZNGatZQ_h51RvLDXgAAAA?rs=1&pid=ImgDetMain'
  ),
  MealsModel(
      id: 'c5',
      title: 'Boli and Groundnuts',
      videoUrl: 'https://www.youtube.com/watch?v=81lrxpl0jVk',
      instructions: [
        "Preheat your grill or oven to medium-high heat.",
        "Make a shallow slit along the length of each plantain, being careful not to cut too deep.",
        "Place the plantains on the grill or in the oven and cook for about 10-15 minutes, turning occasionally, until the skin is blackened and the plantains are soft.",
        "While the plantains are cooking, roast the peanuts in a dry skillet over medium heat until they are lightly browned and fragrant.",
        "Remove the plantains from the heat and let them cool slightly. Peel off the skin and slice the plantains into rounds.",
        "Crush the roasted peanuts in a mortar and pestle or grind them in a food processor until you have a coarse texture.",
        "Serve the sliced plantains with the crushed peanuts and sprinkle with salt to taste.",
        "Enjoy your delicious Boli and Groundnut!",
      ],
      ingredients: [
        "Ripe plantains",
        "Peanuts (groundnuts)",
        "Salt",
      ],
      prepTimeMinutes: 3,
      cookTimeMinutes: 45,
      servings: 3,
      cuisine: 'Nigerian',
      caloriesPerServings: 4,
      rating: 3.0,
      imgUrl: 'https://pbs.twimg.com/media/EYOCpXAXsAANqpG.jpg'
  ),
  MealsModel(id: 'c6',
      title: 'Ewa Agoyin',
      videoUrl: 'https://www.youtube.com/watch?v=PCrUSFtAJKM&t=4s',
      instructions: [
        "Directions for making Ewa Agoyin (Ewa Aganyin):",
        "Pick out the specks of dirt from the beans, rinse and drain the beans a couple of times.",
        "Pour the beans in a stockpot, add the water and cook till it becomes very tender – about 2 to 2½ hours.",
        "Use a Potato Masher or a wooden spoon to mash the Beans to your preference.",
        "Directions for cooking Ewa Agoyin / Ewa Aganyin Stew",
        "Rehydrate the dried Chilies and bell peppers by soaking them in water overnight or pour hot boiling water over them for about 2 hours",
        "Blend the rehydrated Peppers with the onions, ginger, and about a quarter cup of water and set aside.",
        "Preheat the Palm oil in a pan on medium heat until the oil is very hot but not bleached.",
        "Add the sliced onion and let it cook for about 10 to 15 minutes. We want it browned and not black or burnt.",
        "Stir in the blended peppers and cook for about 10 minutes",
        "Add the seasoning cubes, crayfish, and salt to taste.",
        "Leave it to cook for another 5 to 10 minutes; by this time, the color of the pepper would have changed from bright red to dark red. If not, cook for some additional time.",
        "Serve the Sauce over the Ewa Agoyin (Ewa Aganyin) or eat with your Agege Bread and Enjoy!",
      ],
      ingredients: [
        "For the Beans:",
        "1 lb Beans",
        "6-8 Cups Water",
        "salt to taste",
        "For the Sauce:",
        "3/4 Cup Chili Dried",
        "2 Red Bell Pepper Dried",
        "1 Medium Onion",
        "1 Tsp Ginger",
        "2 Tsp Cray Fish",
        "2 Seasoning Cubes",
        "Salt To Taste",
        "1 Cup Palm Oil",
      ],
      prepTimeMinutes: 5,
      cookTimeMinutes: 45 ,
      servings: 4,
      cuisine: 'Nigeria-Yoruba',
      caloriesPerServings: 8,
      rating: 4.7,
      imgUrl: 'https://www.bellanaija.com/wp-content/uploads/2023/08/1AAA64B1-448F-4F16-82B9-91A8DD8A1184.jpeg'
  ),
  MealsModel(id: 'c7',
      title: 'Yam Porridge',
      videoUrl:'https://www.youtube.com/watch?v=nFeYik8ziUQ&t=2s',
      instructions: [
        "Prep the ingredients",
        "peel and cut yam into chunks, rinse and cover with cold water and set aside Roughly blend red bell pepper, scotch bonnet chill and onions together with water and set aside",
        "Boil the fish for about 5 minutes with seasoning cube, salt. Save fish broth for the porridge if you are not using beef stock. De-bone fish, flake and set aside",
        "Place a small pan on medium heat, add palm oil and heat for about 2 minutes. Add chopped onions and fry till onions are translucent. Take it off the heat and set aside. This is to be added to the yam at the tail end of the cooking.",
        "Place a large pan on medium heat; add yam chunks, blended pepper mixture and enough water to cover it (about one cm above the yam or keep it at the same level), add salt, seasoning cube and bring to boil till yam is almost tender. Reduce the heat if you have to avoid the yam burning. Add stock or water to yam in between cooking if need be",
        "Once yam is almost tender add already heated palm oil to the yam and continue to cook till yam is tender. Using a back of a wooden ladle, break yam into pieces but not to puree, leave some yam chunks if you desire",
        "Stir in the flaked fish and stir together gently into the yam to avoid breaking the fish and yam more, cook for another 2-3 minutes. Finally, add chopped spinach (or any other green vegetable), fold into porridge and cook for another 2 minutes. Take it off the heat as the vegetable would continue to cook just before you serve the dish.",
      ],
      ingredients: [
        "½ tuber of yam about 1kg",
        "1 red bell pepper Tatashe",
        "1-2 scotch bonnet chillies (Ata Rodo)",
        "1 onion chopped",
        "½ cup palm oil or use according to preference and you can substitute with vegetable oil",
        "1 tablespoon beef seasoning powder or stock cubes",
        "Salt to taste",
        "1 medium size mackerel fish cleaned (substitute with dry fish or smoked fish)",
        "1 cup Beef stock optional",
        "2 handfuls spinach or any green vegetable",
      ],
      prepTimeMinutes: 5,
      cookTimeMinutes: 25,
      servings: 3,
      cuisine: 'Nigerian',
      caloriesPerServings: 8,
      rating: 5.0,
      imgUrl: 'https://pan-african.net/wp-content/uploads/2021/04/Yam-porridge.jpg'
  ),
  MealsModel(
      id: 'c8',
      title: 'Suya',
      videoUrl: 'https://www.youtube.com/watch?v=c27vMVHEJJ4',
      instructions: ["Cut the steak across the grain into thin strips. Add stock cube, half of the suya spice, and salt to the beef strips. Mix well, cover with clingfilm and leave in the fridge to marinate for at least 30 minutes.",
        "Bring out the marinated beef and thread on pre-soaked skewers. Apply the remaining half of suya spice all over then brush with oil.",
        "Arrange the skewered beef on an oven rack then grill in the oven at a temperature of 175C (fan) for 15 minutes. Turn the beef to the other side and grill for another 10 minutes.",
        "Bring out of the oven, remove Suya from skewers, sprinkle with more suya spice, and serve with sliced onions, tomatoes, and cucumbers. You can also add cabbage. Enjoy delicious, nutty, tasty, smokey Nigerian suya.",],
      ingredients: [
        "Equipment:",
        "Knife",
        "Skewers",
        "Pastry brush",
        "Oven rack",
        "Ingredients:",
        "500 g (1lb) Beef",
        "3 tablespoon Suya Spice halved",
        "1 5g Stock cube",
        "Salt",
        "2 tablespoon Oil",
        "To Serve:",
        "1 tablespoon Suya Spice",
        "1 medium Onion - Red or Brown Sliced",
        "2 Tomatoes Cut",
        "1 Cucumber Sliced",
      ],
      prepTimeMinutes: 6,
      cookTimeMinutes: 45,
      servings: 5,
      cuisine: 'Nigera-Hausa',
      caloriesPerServings: 3,
      rating: 5.0,
      imgUrl: 'https://www.recipevibes.com/wp-content/uploads/2020/09/suya-suya.jpeg'),
  MealsModel(id: 'c9',
      title: 'Kilishi',
      videoUrl: 'https://www.youtube.com/watch?v=0yWRWQC6eiw',
      instructions: [
        "Notes on the ingredients",
        "The beef you will use for Kilishi should be cut from the reddest part of the beef with no fat at all.",
        "Cut the beef as thin as possible. It is usually as thin as 3mm. The Mai Kilishis have the sharpest knife in the world. Their ability to cut a large blanket of beef so thinly is a skill that cannot be rivalled.",
        "Where I live, the butchers have an appliance for cutting beef into very thin fillets. Unfortunately, they cannot get a large blanket of beef so I manage the small pieces the size of my palm.",
        "You can buy the suya spice (suya pepper) in African food stores, you can also make yours. Visit How to make Nigerian Suya Spice for details.",
        "By 3 cloves of garlic I mean 3 small pieces of garlic you get when you break up a bulb of garlic.",
        "Cloves is a spice that gives the Kilishi a unique flavour.",
        "I used fresh ginger but you can use dry ground ones instead.",
        "You only need a small quantity of salt. You may not even need it if you do not eat a lot of salt. Be careful when adding salt else the Kilishi will be over-seasoned when done.",
        "You get the dry cayenne pepper seeds by removing the red part of the pepper.",
        "Prepare the Kilishi Spice Solution:",
        "Grind the cloves with a dry mill and set aside.",
        "Peel the garlic and ginger and pound/grind into a smooth paste.",
        "Add the ground cloves and crushed stock cubes to the garlic and ginger paste.",
        "And some water, stir and sieve to get an extract of these spices and seasoning.",
        "Add the suya spice and cayenne pepper seeds to the solution, stir and set aside.",
        "Directions for making Kilishi:",
        "Cut the beef into very thin fillets if it has not been done for you by the butchers.",
        "Cut off all traces of fat from the beef.",
        "Set your oven to 250°C (475F) or Gas Mark 9 to preheat. If your oven temperature settings are not up to these, use the highest possible setting but this means that your own drying times will change. If your oven has a fan, turn it on as well because it helps dry the beef faster.",
        "Sprinkle a tiny quantity of salt on the fillets of beef and spread them around. You only need a tiny quantity and you can skip salt altogether.",
        "Line your oven tray with a baking sheet and lay the pieces of beef flat on it.",
        "Put the tray of beef into the oven and bake for 15 minutes. Flip the beef every 5 minutes for even drying.",
        "After 15 minutes, bring out the beef from the oven and brush the Kilishi all over them, making sure that both sides of the beef are well covered.",
        "Note:",
        "The way they do it in the North is to dry the fillets of beef in the sun for 2 days then soak them in the Kilishi spice solution and spread in the sun (on flat rafia baskets) till dry.",
        "Some grill it after soaking in the Kilishi solution.",
        "Put them back in the oven and bake for additional 10 to 15 minutes. Flip them from time to time and this time, keep a very good eye on it else it will become bone dry. You want it dry and chewy not crunchy.",
        "Please note that the Kilishi will become drier when it has cooled down completely so bear this in mind when deciding the time to bring it out of the oven.",
        "Serve with more pepper (if you wish) and a chilled drink",
      ],
      ingredients: [
        "10 pieces wafer-thin beef",
        "1 tablespoon suya spice (suya pepper)",
        "3 cloves of garlic",
        "1 teaspoon cloves (Kanafuru)",
        "A small piece of ginger",
        "1 small stock cube",
        "¼ teaspoon salt",
        "1 teaspoon dry cayenne pepper seeds",
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 25,
      servings: 4,
      cuisine: 'Nigeria-Hausa',
      caloriesPerServings: 5,
      rating: 4.5,
      imgUrl: 'https://www.nairaland.com/attachments/16321332_fbimg1665757729305_jpeg9a320663abb017ac5407560041a19c18'),
  MealsModel(id: 'c10',
      title: 'Ofe Aku',
      videoUrl: 'https://www.youtube.com/watch?v=Txg6cWXPaiM',
      instructions: [
        "Boil the beef with the seasoning cubes and half of the chopped onions till done. For best results, I grill the meat in the oven.",
        "Slowly decant the palm fruit concentrate into the pot you will use to cook the Ofe Akwu making sure the unwanted sediments do not go into the pot.",
        "Add the beef stock, the grilled meat, dry fish, the remaining onions, ogiri okpei and pepper and crayfish.",
        "Cover and start cooking. When it boils, continue cooking till you see some red oil floating on top.",
        "Add the smoked mackerel and scent leaves.",
        "Cover and once it boils again, it’s done! Taste and add salt if necessary.",
      ],
      ingredients: [
        "800g palm fruits (5 cups)",
        "1kg (2.2lbs) beef",
        "1 dry fish",
        "2 smoked mackerel (titus fish)",
        "1-2 bulbs of red onion",
        "2 tablespoons ground crayfish",
        "2 small seasoning cubes",
        "1 small lump of ogiri okpei",
        "Habanero pepper (to your taste)",
        "Scent leaves",
      ],
      prepTimeMinutes: 15,
      cookTimeMinutes: 25,
      servings: 5,
      cuisine: 'Nigeria-Igbo',
      caloriesPerServings: 4,
      rating: 4.9,
      imgUrl: 'https://igbodigest.com/wp-content/uploads/2020/08/ofe-akwu.png'
  ),
];